### ISSUE TITLE
Facing issue with model

### ISSUE THREAD

**Issue by hunaidkhan2000** [ncsoft/promotionImpact#5]
Hi first of all i loved the package created by you. Actually i am exploring you package and got an error. I have created a very similar data as your and also for the promotions i have around 8 promotions in my data. for the sales data i have complete 2019 data till date. but when i run model code

```
pri1 <- promotionImpact(data=sales, promotion= promo, 
                        time.field = 'date', target.field = 'sales', 
                        dummy.field = 'month_start', var.type = 'dummy',
                        trend = T, period = 30.5, trend.param = 0.02, period.param = 2,
                        logged = TRUE, differencing = TRUE, synergy.promotion = FALSE,
                        synergy.var = NULL, allow.missing = TRUE)
```
I got the error Error in rowMeans(sapply(smooth.list[[ii]], unlist)) : 
  'x' must be an array of at least two dimensions   

I tried everything but error still persists can you help me which parameter is causing this error. if you need more information do let me know

**Comment by danbi-ncsoft** [comment]
Thank you for your interest in the package.
The problem you mentioned seems to be an error in calculating the smoothed values ​​by matching the promotion_tag and promotion_id in the promo data.
This error can occur if the promotion_tag is changed during promotion and there is a promotion_tag that does not match any promotion_id.
It is difficult to pinpoint the exact cause because there is no data, but I recommend checking the promo data again.

**Comment by danbi-ncsoft** [comment]
If there is only one promotion for a particular promotion category and the 'promotion_id' variable is numeric, that error can occur. So, if your 'promotion_id' variable is numeric, I recommend changing it to a character or factor. I will handle these errors when I update the next version.
